# Site settings
title: Isaac Rowe
header-img: img/lexington-center.jpg
email: irowe.bbn@gmail.com
description: "Thoughts on Life, the Universe and Everything"
baseurl: ""
url: "http://isaacrowe.net"
twitter_username: Isaac_rowe1
github_username:  irowebbn

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
