# Site settings
title: Isaac's Blog
email: irowe.bbn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "isaacrowe.net" # the base hostname & protocol for your site
twitter_username: Isaac_rowe1
github_username:  irowebbn

# Build settings
markdown: kramdown
permalink: pretty
